name: "D Compiler Installation"
description: "Installs the requested D compiler"
author: "Mihails Strasuns"
inputs:
  compiler:
    description: "Compiler version string, for example 'dmd-latest' or 'ldc-1.20.1'"
    required: false
  dub:
    description: "DUB version string, for example 'any', 'latest', or, '1.29.0'"
    default: any
    required: false
  gh_token:
    description: "Token to use when doing Github API request (for ldc-master)"
    default: ${{ github.token }}
    required: false
  gdmd_sha:
    description: "Commit sha in https://github.com/D-Programming-GDC/gdmd, used only by the gdmd compiler"
    default: 'latest'
  verify_sig:
    description: "Verify downloaded artifacts, if a signature file is present"
    default: true
    required: false
    type: boolean
runs:
  using: "node20"
  main: "dist/index.js"
