name: "D Compiler Installation"
description: "Installs the requested D compiler"
author: "Mihails Strasuns"
inputs:
  compiler:
    description: "Compiler version string, for example 'dmd-latest' or 'ldc-1.20.1'"
    default: "dmd-latest"
  gh_token:
    description: "Token to use when doing Github API request (for ldc-master)"
    default: ${{ github.token }}
    required: false
runs:
  using: "node12"
  main: "lib/main.js"
