name: "D Compiler Installation"
description: "Installs the requested D compiler"
author: "Mihails Strasuns"
inputs:
  compiler:
    description: "Compiler version string, for example dmd-2.088.0"
    default: "dmd-2.088.0"
runs:
  using: "node12"
  main: "lib/main.js"
